Repository WeBankPartners/wecube-plugins-artifacts, pull requests merged in 2020-08, with the labels that each got.

#127 #123 Update i18n config
  artifacts-ui/src/locale/i18n/en-US.json
  artifacts-ui/src/locale/i18n/zh-CN.json
Labels: enhancement

#143 #142 Set modal closing strategy
  artifacts-ui/src/views/artifacts.vue
Labels: enhancement

#152 150 upgrade system design list display
  artifacts-ui/src/locale/i18n/en-US.json
  artifacts-ui/src/locale/i18n/zh-CN.json
  artifacts-ui/src/views/artifacts.vue
Labels: enhancement

#155 #154 Highlight table row
  artifacts-ui/src/components/simple-table.vue
  artifacts-ui/src/views/artifacts.vue
Labels: enhancement

#160 Bug fix
  artifacts-ui/src/api/base.js
  artifacts-ui/src/views/artifacts.vue
Labels: bug

#134 #132 message normalization
  .gitignore
  artifacts-core/.gitignore
  artifacts-core/src/main/java/com/webank/plugins/artifacts/commons/PluginException.java
  artifacts-core/src/main/java/com/webank/plugins/artifacts/controller/ArtifactManagementController.java
  artifacts-core/src/main/java/com/webank/plugins/artifacts/interceptor/GlobalExceptionHandler.java
  artifacts-core/src/main/java/com/webank/plugins/artifacts/service/ArtifactService.java
  artifacts-core/src/main/resources/application.yml
  artifacts-core/src/main/resources/message/artifacts_core_err_message.properties
Labels: Dont Merge
